Tue, 29 Nov 2022 18:30:10 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:30:10 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:30:16 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:16 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | [27291] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:16 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717816181985200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27289' | DISCONNECT
Tue, 29 Nov 2022 18:30:17 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | [27293] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:18 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717817729322400' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27292' | DISCONNECT
Tue, 29 Nov 2022 18:30:19 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:19 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | [27295] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:19 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717819024621000' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27294' | DISCONNECT
Tue, 29 Nov 2022 18:30:20 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:20 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | [27297] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:20 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717820288259700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27296' | DISCONNECT
Tue, 29 Nov 2022 18:30:23 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:30:23 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:30:25 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:25 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | [27312] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:26 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717825447014200' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27310' | DISCONNECT
Tue, 29 Nov 2022 18:30:26 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:27 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | [27314] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:27 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717826640969500' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27313' | DISCONNECT
Tue, 29 Nov 2022 18:30:27 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:28 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | [27316] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:28 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717827798697100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27315' | DISCONNECT
Tue, 29 Nov 2022 18:30:29 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:30:29 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:30:32 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:33 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | [27331] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:33 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717832490348300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27329' | DISCONNECT
Tue, 29 Nov 2022 18:30:34 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "serial/serialposix.py", line 332, in open
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:30:35 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | [27333] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:30:35 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717834767777100' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27332' | DISCONNECT
Tue, 29 Nov 2022 18:31:31 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 353, in __init__
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "esptool.py", line 369, in _set_port_baudrate
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "serial/serialutil.py", line 299, in baudrate
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' |   File "serial/serialposix.py", line 517, in _reconfigure_port
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | termios.error: (5, 'Input/output error')
Tue, 29 Nov 2022 18:31:32 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | [27340] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:31:32 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717891486424800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27339' | DISCONNECT
Tue, 29 Nov 2022 18:31:47 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS16 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:31:47 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:31:48 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717908539217800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:31:49 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717908539217800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27356' | DISCONNECT
Tue, 29 Nov 2022 18:31:58 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "serial/serialposix.py", line 322, in open
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | OSError: [Errno 5] Input/output error: '/dev/ttyS16'
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | 
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | During handling of the above exception, another exception occurred:
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | 
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 4782, in main
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 115, in get_default_connected_device
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "esptool.py", line 345, in __init__
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "serial/__init__.py", line 90, in serial_for_url
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' |   File "serial/serialposix.py", line 325, in open
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | serial.serialutil.SerialException: [Errno 5] could not open port /dev/ttyS16: [Errno 5] Input/output error: '/dev/ttyS16'
Tue, 29 Nov 2022 18:31:59 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | [27360] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:31:59 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717918671778900' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27359' | DISCONNECT
Tue, 29 Nov 2022 18:32:02 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:32:02 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:32:03 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 483, in command
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "esptool.py", line 446, in write
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' |   File "serial/serialposix.py", line 663, in write
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | serial.serialutil.SerialTimeoutException: Write timeout
Tue, 29 Nov 2022 18:32:18 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | [27375] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:32:18 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669717923959595300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27373' | DISCONNECT
Tue, 29 Nov 2022 18:34:43 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 483, in command
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "esptool.py", line 446, in write
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' |   File "serial/serialposix.py", line 663, in write
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | serial.serialutil.SerialTimeoutException: Write timeout
Tue, 29 Nov 2022 18:34:58 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | [27384] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:34:58 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718083900455300' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27383' | DISCONNECT
Tue, 29 Nov 2022 18:37:50 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718270320880800' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:38:49 +0800 | INFO   | server     |  | Serving using application   : /mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool -p /dev/ttyS11 -b 460800 --before default_reset --after hard_reset --chip esp32-s3 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 /mnt/d/2022/python/esptool_server/esptool_server_py/upload_file/ab99c2c8-6d6f-4019-bd36-a15d8b6dfdb6.bin
Tue, 29 Nov 2022 18:38:49 +0800 | INFO   | server     |  | Starting WebSocket server   : ws://LAPTOP-TK9NNM60:8083/
Tue, 29 Nov 2022 18:38:50 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' | CONNECT
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | Traceback (most recent call last):
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 5482, in <module>
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 5475, in _main
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 4895, in main
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 3911, in detect_flash_size
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 886, in flash_id
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 1198, in run_spiflash_command
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 733, in read_reg
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 483, in command
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "esptool.py", line 446, in write
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' |   File "serial/serialposix.py", line 663, in write
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | serial.serialutil.SerialTimeoutException: Write timeout
Tue, 29 Nov 2022 18:39:05 +0800 | ERROR  | stderr     | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | [27477] Failed to execute script 'esptool' due to unhandled exception!
Tue, 29 Nov 2022 18:39:05 +0800 | ACCESS | session    | url:'http://localhost:8083/' id:'1669718330947926700' remote:'::1' command:'/mnt/d/2022/python/esptool_server/esptool_server_py/tools/esptool' origin:'http://www.websocket-test.com' pid:'27475' | DISCONNECT
